## Module 1: Introduction

This module consists of NumPy library introduction, linear algebra refreshments and Pandas introduction.

### Part 1: Numpy

In [2]:
# import numpy to use 
import numpy as np

# create arrays
print("Array of zeros:", np.zeros(10))
print("Array of ones:", np.ones(10))
print("Array of arbitrary number:", np.full(10, 2.5))

a = np.array([1, 2, 3, 4, 5])
print("Python list as np array:", a)
print("Element of the array:", a[2])
a[2] = 10
print("Array with changed element:", a)

print("Array with a range:", np.arange(3, 10))
print("Array with linspace:", np.linspace(0, 100, 11))

Array of zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of arbitrary number: [2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]
Python list as np array: [1 2 3 4 5]
Element of the array: 3
Array with changed element: [ 1  2 10  4  5]
Array with a range: [3 4 5 6 7 8 9]
Array with linspace: [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [3]:
# create multi-dimensional arrays
print("Multi-dim zeros:\n", np.zeros((2, 5)))

n = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nMulti-dim array:\n", n)
print("\nElement of the multi-dim array:", n[0, 1])
n[0, 1] = 20
print("Multi-dim array with changed element:\n", n)

print("\nRow of the multi-dim array:", n[1])
n[1] = [1, 1, 1]
print("Multi-dim array with changed row:\n", n)

print("\nColumn of the multi-dim array:", n[:, 1])
n[:, 1] = [2, 2, 2]
print("Multi-dim array with changed column:\n", n)

Multi-dim zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Multi-dim array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Element of the multi-dim array: 2
Multi-dim array with changed element:
 [[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]

Row of the multi-dim array: [4 5 6]
Multi-dim array with changed row:
 [[ 1 20  3]
 [ 1  1  1]
 [ 7  8  9]]

Column of the multi-dim array: [20  1  8]
Multi-dim array with changed column:
 [[1 2 3]
 [1 2 1]
 [7 2 9]]


In [4]:
# create randomly generated arrays
np.random.seed(2) # added for reproducibility
print("2D uniform dist random array:\n", np.random.rand(5, 2))

print("\n2D normal dist random array:\n", np.random.randn(5, 2))

print("\n2D integer random array with limits:\n", np.random.randint(low=0, high=100, size=(5, 2)))

2D uniform dist random array:
 [[0.4359949  0.02592623]
 [0.54966248 0.43532239]
 [0.4203678  0.33033482]
 [0.20464863 0.61927097]
 [0.29965467 0.26682728]]

2D normal dist random array:
 [[ 0.55145404  2.29220801]
 [ 0.04153939 -1.11792545]
 [ 0.53905832 -0.5961597 ]
 [-0.0191305   1.17500122]
 [-0.74787095  0.00902525]]

2D integer random array with limits:
 [[83 31]
 [66 80]
 [52 76]
 [50  4]
 [90 63]]


In [5]:
# element-wise operations
a = np.arange(5)
print("Array a:", a)
print("Array with elements +1:", a+1)
print("Array with elements *1:", a*2)
print("Array with elements /100:", a/100)
print("Array with elements **2:", a**2)

b = (10 + (a * 2)) **2 / 100
print("Array b:", b)

print("Array a + b:", a + b)
print("Array a / b:", a / b)

Array a: [0 1 2 3 4]
Array with elements +1: [1 2 3 4 5]
Array with elements *1: [0 2 4 6 8]
Array with elements /100: [0.   0.01 0.02 0.03 0.04]
Array with elements **2: [ 0  1  4  9 16]
Array b: [1.   1.44 1.96 2.56 3.24]
Array a + b: [1.   2.44 3.96 5.56 7.24]
Array a / b: [0.         0.69444444 1.02040816 1.171875   1.2345679 ]


In [8]:
# comparison operations
print("Array a:", a)
print("Array b:", b)

print("Array a >= 2:", a >= 2)
print("Array a > b:", a > b)

print("Array a[a > b]:", a[a > b])

Array a: [0 1 2 3 4]
Array b: [1.   1.44 1.96 2.56 3.24]
Array a >= 2: [False False  True  True  True]
Array a > b: [False False  True  True  True]
Array a[a > b]: [2 3 4]
